---
- hosts: all
  tasks:
    - name: ensure pip is installed
      apt: pkg=python-pip 
           state=latest
           update-cache=yes

    - name: ensure ntpd is at the latest version
      apt: pkg=ntp state=latest
      notify:
      - restart ntpd

  handlers:
    - name: restart ntpd
      service: name=ntpd state=restarted
